# Generated by Django 3.0.2 on 2020-01-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekkentiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tierlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tierData', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='character_portrait',
            field=models.ImageField(upload_to='portraits/'),
        ),
        migrations.DeleteModel(
            name='Tier',
        ),
    ]
