# Generated by Django 3.0.2 on 2020-01-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekkentiers', '0002_auto_20200120_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierlist',
            name='tierData',
            field=models.TextField(),
        ),
    ]
