# Generated by Django 3.0.2 on 2020-01-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekkentiers', '0003_auto_20200120_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tierlist',
            name='tierData',
        ),
    ]
