# Generated by Django 3.0.2 on 2020-01-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekkentiers', '0005_auto_20200120_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tierlist',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='tierlist',
            name='tiers',
        ),
        migrations.AddField(
            model_name='tierlist',
            name='tierlist',
            field=models.TextField(null=True),
        ),
    ]
